# JWT Configuration
jwt:
  secret: 2?Q:mba;7mvN[^0=Ixw54z@YOiySC!TqGF)-20tOL`*qs^AlK_|gYoS;ah0r2Oj
  expiration: 86400000  # 24 hours in milliseconds
  issuer: 'Osas Project'
  audience: myShoppingCart
  prefix: "Bearer "
  excluded.urls: >
      - /user/login
      - /products/signup
      - /user/reset/*
      - /test/**
      - /actuator/**
      - /error

# Client Configuration
client:
  url: http://localhost:3000
  email:
    verify:
      param: user/verifyEmail
      expiration: 86400000
    reset:
      param: user/resetPassword
      expiration: 86400000
      
# H2 Server Configuration 
h2.server:
  params: >
    -tcp, 
    -tcpAllowOthers, 
    -tcpPort, 
    9090
